name: maataara_sacco_calculator
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  freezed_annotation: ^2.0.3
  telephony: ^0.2.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: 
  flutter_test:
    sdk: flutter
  freezed: 
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

scripts:
  build: fvm flutter pub run build_runner build --delete-conflicting-outputs
  watch: fvm flutter pub run build_runner watch --delete-conflicting-outputs
  buildapp: fvm flutter build appbundle
  test: fvm flutter test